/**
 * Extra static EN→AR city labels for CSC spellings missing from i18n-iso-cities.
 * Keys are normalizeKey()-compatible Latin names (diacritics stripped).
 */
export const CITY_AR_OVERRIDES: Record<string, Record<string, string>> = {
  EG: {
    halwan: "حلوان",
    helwan: "حلوان",
    "10th of ramadan": "العاشر من رمضان",
    "abu simbel": "أبو سمبل",
    "ain sukhna": "العين السخنة",
    luxor: "الأقصر",
    giza: "الجيزة",
    "6th of october": "السادس من أكتوبر",
    "sheikh zayed": "الشيخ زايد",
    obour: "العبور",
    "el obour": "العبور",
    banha: "بنها",
    damanhur: "دمنهور",
    damanhour: "دمنهور",
    mahalla: "المحلة",
    "el mahalla": "المحلة الكبرى",
    "el mahalla el kubra": "المحلة الكبرى",
    kafr: "كفر",
    "kafr el sheikh": "كفر الشيخ",
    "shibin el kom": "شبين الكوم",
    arish: "العريش",
    "el arish": "العريش",
    matruh: "مرسى مطروح",
    "marsa matruh": "مرسى مطروح",
    hurghada: "الغردقة",
    "sharm el sheikh": "شرم الشيخ",
    dahab: "دهب",
    nuweiba: "نويبع",
    taba: "طابا",
  },
  SA: {
    jeddah: "جدة",
    jiddah: "جدة",
    dammam: "الدمام",
    khobar: "الخبر",
    "al khobar": "الخبر",
    dhahran: "الظهران",
    taif: "الطائف",
    "at taif": "الطائف",
    abha: "أبها",
    "khamis mushait": "خميس مشيط",
    jubail: "الجبيل",
    yanbu: "ينبع",
    buraidah: "بريدة",
    buraydah: "بريدة",
    hofuf: "الهفوف",
    "al ahsa": "الأحساء",
    ahsa: "الأحساء",
    qatif: "القطيف",
    "al qatif": "القطيف",
    sakaka: "سكاكا",
    arar: "عرعر",
    jazan: "جازان",
    najran: "نجران",
    hail: "حائل",
    tabuk: "تبوك",
  },
  AE: {
    "abu dhabi": "أبوظبي",
    "abu dhabi municipality": "أبوظبي",
    "abu dhabi island and internal islands city": "أبوظبي",
    "al ain": "العين",
    "al ain city": "العين",
    "al ain municipality": "العين",
    dubai: "دبي",
    sharjah: "الشارقة",
    ajman: "عجمان",
    fujairah: "الفجيرة",
    "ras al khaimah": "رأس الخيمة",
    "umm al quwain": "أم القيوين",
  },
  JO: {
    amman: "عمّان",
    irbid: "إربد",
    zarqa: "الزرقاء",
    aqaba: "العقبة",
    madaba: "مأدبا",
    salt: "السلط",
    karak: "الكرك",
    jerash: "جرش",
    ajloun: "عجلون",
    mafraq: "المفرق",
  },
};
